In [2]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import tensorflow as tf

In [3]:
df = pd.read_csv('speed_dating.csv')
df.head()

,has_null,wave,gender,age,age_o,d_age,d_d_age,race,race_o,samerace,...,expected_num_matches,d_expected_happy_with_sd_people,d_expected_num_interested_in_me,d_expected_num_matches,like,guess_prob_liked,d_like,d_guess_prob_liked,met,match
0,0,1.0,female,21.0,27.0,6.0,[4-6],Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,...,4.0,[0-4],[0-3],[3-5],7.0,6.0,[6-8],[5-6],0.0,0
1,0,1.0,female,21.0,22.0,1.0,[0-1],Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,...,4.0,[0-4],[0-3],[3-5],7.0,5.0,[6-8],[5-6],1.0,0
2,1,1.0,female,21.0,22.0,1.0,[0-1],Asian/Pacific Islander/Asian-American,Asian/Pacific Islander/Asian-American,1,...,4.0,[0-4],[0-3],[3-5],7.0,5.0,[6-8],[0-4],1.0,1
3,0,1.0,female,21.0,23.0,2.0,[2-3],Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,...,4.0,[0-4],[0-3],[3-5],7.0,6.0,[6-8],[5-6],0.0,1
4,0,1.0,female,21.0,24.0,3.0,[2-3],Asian/Pacific Islander/Asian-American,Latino/Hispanic American,0,...,4.0,[0-4],[0-3],[3-5],6.0,6.0,[6-8],[5-6],0.0,1

In [11]:
df.dtypes=='object'

has_null              False
wave                  False
gender                 True
age                   False
age_o                 False
                      ...
guess_prob_liked      False
d_like                 True
d_guess_prob_liked     True
met                   False
match                 False
Length: 120, dtype: bool

### Feature exploration

In [3]:
i = 0
for col in df.columns:
    if df[col].dtype == 'object':
        print(col, ': ', len(df[col].unique()))
        print(df[col].value_counts())
        i += 1
print(i)

gender :  2
male      4194
female    4184
Name: gender, dtype: int64
d_d_age :  4
[2-3]     2406
[4-6]     2316
[0-1]     2227
[7-37]    1429
Name: d_d_age, dtype: int64
race :  5
European/Caucasian-American              4790
Asian/Pacific Islander/Asian-American    1982
Latino/Hispanic American                  664
Other                                     522
Black/African American                    420
Name: race, dtype: int64
race_o :  5
European/Caucasian-American              4795
Asian/Pacific Islander/Asian-American    1978
Latino/Hispanic American                  664
Other                                     521
Black/African American                    420
Name: race_o, dtype: int64
d_importance_same_race :  3
[2-5]     3104
[0-1]     2885
[6-10]    2389
Name: d_importance_same_race, dtype: int64
d_importance_same_religion :  3
[0-1]     3111
[2-5]     3013
[6-10]    2254
Name: d_importance_same_religion, dtype: int64
field :  259
Business                          584
MBA                               468
Law                               462
Social Work                       378
International Affairs             252
                                 ...
Business [Finance & Marketing]      6
Stats                               6
MFA  Poetry                         6
marine geophysics                   5
theory                              5
Name: field, Length: 259, dtype: int64
d_pref_o_attractive :  3
[21-100]    3010
[16-20]     2874
[0-15]      2494
Name: d_pref_o_attractive, dtype: int64
d_pref_o_sincere :  3
[16-20]     3820
[0-15]      3065
[21-100]    1493
Name: d_pref_o_sincere, dtype: int64
d_pref_o_intelligence :  3
[16-20]     4272
[21-100]    2517
[0-15]      1589
Name: d_pref_o_intelligence, dtype: int64
d_pref_o_funny :  3
[16-20]     3870
[0-15]      3188
[21-100]    1320
Name: d_pref_o_funny, dtype: int64
d_pref_o_ambitious :  3
[0-15]      6680
[16-20]     1603
[21-100]      95
Name: d_pref_o_ambitious, dtype: int64
d_pref_o_shared_interests :  3
[0-15]      6085
[16-20]     1962
[21-100]     331
Name: d_pref_o_shared_interests, dtype: int64
d_attractive_o :  3
[6-8]     4537
[0-5]     2971
[9-10]     870
Name: d_attractive_o, dtype: int64
d_sinsere_o :  3
[6-8]     5192
[9-10]    1665
[0-5]     1521
Name: d_sinsere_o, dtype: int64
d_intelligence_o :  3
[6-8]     5379
[9-10]    1782
[0-5]     1217
Name: d_intelligence_o, dtype: int64
d_funny_o :  3
[6-8]     4645
[0-5]     2744
[9-10]     989
Name: d_funny_o, dtype: int64
d_ambitous_o :  3
[6-8]     4613
[0-5]     2505
[9-10]    1260
Name: d_ambitous_o, dtype: int64
d_shared_interests_o :  3
[0-5]     4690
[6-8]     3172
[9-10]     516
Name: d_shared_interests_o, dtype: int64
d_attractive_important :  3
[21-100]    3019
[16-20]     2875
[0-15]      2484
Name: d_attractive_important, dtype: int64
d_sincere_important :  3
[16-20]     3821
[0-15]      3062
[21-100]    1495
Name: d_sincere_important, dtype: int64
d_intellicence_important :  3
[16-20]     4276
[21-100]    2518
[0-15]      1584
Name: d_intellicence_important, dtype: int64
d_funny_important :  3
[16-20]     3874
[0-15]      3184
[21-100]    1320
Name: d_funny_important, dtype: int64
d_ambtition_important :  3
[0-15]      6680
[16-20]     1603
[21-100]      95
Name: d_ambtition_important, dtype: int64
d_shared_interests_important :  3
[0-15]      6083
[16-20]     1964
[21-100]     331
Name: d_shared_interests_important, dtype: int64
d_attractive :  3
[6-8]     6231
[0-5]     1150
[9-10]     997
Name: d_attractive, dtype: int64
d_sincere :  3
[9-10]    4084
[6-8]     3881
[0-5]      413
Name: d_sincere, dtype: int64
d_intelligence :  3
[6-8]     4929
[9-10]    2701
[0-5]      748
Name: d_intelligence, dtype: int64
d_funny :  3
[6-8]     4244
[9-10]    3934
[0-5]      200
Name: d_funny, dtype: int64
d_ambition :  3
[6-8]     4407
[9-10]    2733
[0-5]     1238
Name: d_ambition, dtype: int64
d_attractive_partner :  3
[6-8]     4545
[0-5]     2963
[9-10]     870
Name: d_attractive_partner, dtype: int64
d_sincere_partner :  3
[6-8]     5198
[9-10]    1667
[0-5]     1513
Name: d_sincere_partner, dtype: int64
d_intelligence_partner :  3
[6-8]     5385
[9-10]    1784
[0-5]     1209
Name: d_intelligence_partner, dtype: int64
d_funny_partner :  3
[6-8]     4651
[0-5]     2737
[9-10]     990
Name: d_funny_partner, dtype: int64
d_ambition_partner :  3
[6-8]     4618
[0-5]     2500
[9-10]    1260
Name: d_ambition_partner, dtype: int64
d_shared_interests_partner :  3
[0-5]     4686
[6-8]     3176
[9-10]     516
Name: d_shared_interests_partner, dtype: int64
d_sports :  3
[6-8]     3239
[0-5]     3018
[9-10]    2121
Name: d_sports, dtype: int64
d_tvsports :  3
[0-5]     5219
[6-8]     2319
[9-10]     840
Name: d_tvsports, dtype: int64
d_exercise :  3
[6-8]     3718
[0-5]     3075
[9-10]    1585
Name: d_exercise, dtype: int64
d_dining :  3
[6-8]     4147
[9-10]    3167
[0-5]     1064
Name: d_dining, dtype: int64
d_museums :  3
[6-8]     4299
[9-10]    2079
[0-5]     2000
Name: d_museums, dtype: int64
d_art :  3
[6-8]     3994
[0-5]     2553
[9-10]    1831
Name: d_art, dtype: int64
d_hiking :  3
[0-5]     3751
[6-8]     3373
[9-10]    1254
Name: d_hiking, dtype: int64
d_gaming :  3
[0-5]     6109
[6-8]     1924
[9-10]     345
Name: d_gaming, dtype: int64
d_clubbing :  3
[6-8]     3831
[0-5]     3455
[9-10]    1092
Name: d_clubbing, dtype: int64
d_reading :  3
[6-8]     3659
[9-10]    3429
[0-5]     1290
Name: d_reading, dtype: int64
d_tv :  3
[0-5]     4158
[6-8]     3397
[9-10]     823
Name: d_tv, dtype: int64
d_theater :  3
[6-8]     3906
[0-5]     2388
[9-10]    2084
Name: d_theater, dtype: int64
d_movies :  3
[6-8]     4152
[9-10]    3424
[0-5]      802
Name: d_movies, dtype: int64
d_concerts :  3
[6-8]     4179
[0-5]     2182
[9-10]    2017
Name: d_concerts, dtype: int64
d_music :  3
[6-8]     3941
[9-10]    3422
[0-5]     1015
Name: d_music, dtype: int64
d_shopping :  3
[0-5]     3975
[6-8]     3033
[9-10]    1370
Name: d_shopping, dtype: int64
d_yoga :  3
[0-5]     5444
[6-8]     2197
[9-10]     737
Name: d_yoga, dtype: int64
d_interests_correlate :  3
[0-0.33]    3063
[0.33-1]    2931
[-1-0]      2384
Name: d_interests_correlate, dtype: int64
d_expected_happy_with_sd_people :  3
[5-6]     4036
[7-10]    2329
[0-4]     2013
Name: d_expected_happy_with_sd_people, dtype: int64
d_expected_num_interested_in_me :  3
[0-3]      7346
[4-9]       654
[10-20]     378
Name: d_expected_num_interested_in_me, dtype: int64
d_expected_num_matches :  3
[0-2]     4514
[3-5]     2900
[5-18]     964
Name: d_expected_num_matches, dtype: int64
d_like :  3
[6-8]     4827
[0-5]     2944
[9-10]     607
Name: d_like, dtype: int64
d_guess_prob_liked :  3
[5-6]     3199
[0-4]     2954
[7-10]    2225
Name: d_guess_prob_liked, dtype: int64
59

#### Insight of the 'field' feature

In [4]:
df['field'].unique()

array(['Law', 'law', 'Economics', 'Masters in Public Administration',
       'Masters of Social Work&Education', 'Finance', 'Business',
       'political science', 'money', 'Operations Research',
       'TC [Health Ed]', 'Psychology', 'social work', 'Social Work',
       'Speech Language Pathology', 'Speech Languahe Pathology',
       'Educational Psychology', 'Applied Maths/Econs', 'Mathematics',
       'Statistics', 'Organizational Psychology',
       'Mechanical Engineering', 'Finanace', 'Finance&Economics',
       'Undergrad - GS', 'Mathematical Finance', 'Medicine', 'MBA', 'LAW',
       'psychology', 'German Literature',
       'Business & International Affairs', 'MFA Creative Writing',
       'Engineering', 'Electrical Engineering', 'Classics',
       'Operations Research [SEAS]', 'chemistry', 'Journalism',
       'Elementary/Childhood Education [MA]', 'microbiology',
       'Masters of Social Work', 'Communications', 'Marketing',
       'Chemistry', 'International Educational Development',
       'Education Administration', 'Business [MBA]', 'Computer Science',
       'Climate-Earth and Environ. Science', 'financial math',
       'Business- MBA', 'Religion', 'Film', 'Sociology',
       'Economics; English', 'Economics; Sociology', 'Polish', 'English',
       'psychology and english', 'Biomedical Engineering',
       'Economics and Political Science', 'Art History/medicine',
       'philosophy', 'electrical engineering', 'marine geophysics',
       'theory', 'engineering', 'Nutrition/Genetics', 'Neuroscience',
       'Comparative Literature', 'International Relations',
       'History of Religion',
       'international affairs - economic development',
       'Political Science', 'Modern Chinese Literature', 'business',
       'Business; marketing', 'physics [astrophysics]', 'Physics',
       'Business/ Finance/ Real Estate', 'Biochemistry', 'Art Education',
       'Philosophy', 'American Studies [Masters]', 'biology',
       'Cell Biology', 'Microbiology', 'math',
       'International Affairs/Finance', 'International Affairs',
       'international affairs/international finance', 'Health policy',
       'English and Comp Lit', 'international finance and business',
       'Sociomedical Sciences- School of Public Health', 'Epidemiology',
       'Social work', 'International Business', 'Medical Informatics',
       'International Finance; Economic Policy', 'Law and Social Work',
       'International Development', 'Business/Law', 'Clinical Psychology',
       'Religion; GSAS', 'International Affairs and Public Health',
       'International affairs', 'History',
       'Business and International Affairs [MBA/MIA Dual Degree]', 'QMSS',
       'climate change', 'Public Administration', 'MA Biotechnology',
       'International Affairs/Business', 'Ecology',
       'Master in Public Administration', 'Computational Biochemsistry',
       'Neurobiology', 'Mathematics; PhD', 'History [GSAS - PhD]',
       'biomedicine', 'Master of International Affairs',
       'Sociology and Education', 'elementary education', 'Biology',
       'American Studies', 'Arts Administration', 'Conservation biology',
       'sociology', 'Japanese Literature', 'biotechnology',
       'Earth and Environmental Science', 'Philosophy [Ph.D.]',
       'Philosophy and Physics', 'nutrition', 'MA Science Education',
       'Genetics', 'Law and English Literature [J.D./Ph.D.]', 'french',
       'Nutritiron', 'GS Postbacc PreMed', 'Art History',
       'Molecular Biology', 'Genetics & Development',
       'medical informatics', 'Electrical Engg.', 'Business School',
       'International Politics',
       'MBA / Master of International Affairs [SIPA]', 'genetics',
       'medicine and biochemistry', 'Social Studies Education',
       'MA Teaching Social Studies', 'Education Policy',
       'Education- Literacy Specialist', 'Anthropology/Education',
       'bilingual education', 'speech pathology', 'Education',
       'Speech Pathology', 'math education', 'TESOL',
       'Elementary Education', 'Cognitive Studies in Education',
       'education', 'Finance/Economics', 'Museum Anthropology',
       'Environmental Engineering', 'Business Administration',
       'Curriculum and Teaching/Giftedness', 'Anthropology',
       'Instructional Tech & Media', 'School Psychology',
       'Instructional Media and Technology', 'SIPA / MIA',
       'English Education', 'art education', 'MA in Quantitative Methods',
       'Early Childhood Education', 'anthropology', 'Architecture',
       'Urban Planning', 'Ed.D. in higher education policy at TC',
       'International Security Policy - SIPA', 'Nutrition', 'EDUCATION',
       'Applied Physiology & Nutrition', 'music education',
       'Music Education', 'Counseling Psychology',
       'Communications in Education', 'Intellectual Property Law',
       'MBA Finance', 'Intrernational Affairs', 'BUSINESS CONSULTING',
       'business school', 'Business; Media', 'MFA -Film',
       'Higher Ed. - M.A.', 'Neuroscience and Education',
       'Creative Writing', 'Creative Writing - Nonfiction',
       'Writing: Literary Nonfiction', 'Creative Writing [Nonfiction]',
       'NonFiction Writing', 'Theatre Management & Producing',
       'Financial Engineering', 'biomedical engineering',
       'Fundraising Management', 'Business [Finance & Marketing]',
       'Elementary Education - Preservice',
       'Education Leadership - Public School Administration',
       'MFA Writing', 'Bilingual Education',
       'International Affairs - Economic Policy', 'SIPA - Energy',
       'Public Policy', 'Law/Business', 'MFA  Poetry', 'SOA -- writing',
       'biomedical informatics', 'physics', 'art history', 'working',
       'Consulting', 'Human Rights: Middle East', 'Human Rights',
       'medicine', 'Biotechnology', 'SIPA-International Affairs',
       'teaching of English', 'GSAS', 'African-American Studies/History',
       'Neurosciences/Stem cells', 'film', 'journalism', 'Theater',
       'Biology PhD', 'biochemistry/genetics', 'epidemiology', 'Stats',
       'math of finance', 'MFA Acting Program', 'Nonfiction writing',
       'Biochemistry & Molecular Biophysics', 'Acting',
       'Social Work/SIPA', 'Public Health', 'ELECTRICAL ENGINEERING',
       'Math', 'Biomedical engineering', 'Industrial Engineering',
       'Industrial Engineering/Operations Research',
       'Masters of Industrial Engineering', 'Biomedical Informatics',
       'MBA - Private Equity / Real Estate', 'General management/finance',
       'Climate Dynamics'], dtype=object)